// JVIN Cruise Dashboard - Main Application Logic
// Secure GitHub JSON Edition

document.addEventListener('DOMContentLoaded', () => {

    // DOM Elements
    const tableBodyEl = document.getElementById('table-body');

    // GitHub Pages cross-repo navigation compatibility
    const btnBack = document.getElementById('btnBack');
    if (btnBack && window.location.hostname.includes('github.io')) {
        btnBack.setAttribute('href', '../travis-airports/');
    }

    // KPI Elements
    const kpiShipsEl = document.getElementById('kpi-ships');
    const kpiPassengersEl = document.getElementById('kpi-passengers');
    const kpiPortsEl = document.getElementById('kpi-ports');
    const kpiUpdatedTimeEl = document.getElementById('kpi-updated-time');
    const kpiUpdatedDateEl = document.getElementById('kpi-updated-date');

    // Hero clock / footer elements
    const liveClockEl = document.getElementById('live-clock');
    const liveAmpmEl = document.getElementById('live-ampm');
    const liveDateEl = document.getElementById('live-date');
    const footerUpdatedEl = document.getElementById('footer-updated');

    // ============================================================
    // SECURE DATA CONFIGURATION
    // ============================================================
    // cruise-data.json is generated by GitHub Actions.
    // The private Apify token NEVER reaches this browser.
    const CRUISE_DATA_URL = 'cruise-data.json';

    // Dashboard checks the existing JSON every 15 minutes.
    // This DOES NOT start a paid Apify run.
    const AUTO_REFRESH_INTERVAL = 900000;

    /**
     * Updates the Last Updated KPI and footer timestamp
     * using Jamaica local time.
     */
    function updateLastUpdatedTimestamp() {
        const now = new Date();
        const jamaicaTime = new Date(now.getTime() - (5 * 60 * 60 * 1000));

        let hours = jamaicaTime.getUTCHours();
        const minutes = jamaicaTime.getUTCMinutes();
        const ampm = hours >= 12 ? 'PM' : 'AM';

        hours = hours % 12;
        if (hours === 0) hours = 12;

        const timeStr =
            `${hours}:${String(minutes).padStart(2, '0')} ${ampm}`;

        const months = [
            'January',
            'February',
            'March',
            'April',
            'May',
            'June',
            'July',
            'August',
            'September',
            'October',
            'November',
            'December'
        ];

        const dateStr =
            `${months[jamaicaTime.getUTCMonth()]} ` +
            `${jamaicaTime.getUTCDate()}, ` +
            `${jamaicaTime.getUTCFullYear()}`;

        if (kpiUpdatedTimeEl) {
            kpiUpdatedTimeEl.textContent = timeStr;
        }

        if (kpiUpdatedDateEl) {
            kpiUpdatedDateEl.textContent = dateStr;
        }

        if (footerUpdatedEl) {
            footerUpdatedEl.textContent =
                `${dateStr} | ${timeStr}`;
        }
    }

    // ============================================================
    // SHIP CAPACITY LOOKUP
    // ============================================================

    const SHIP_CAPACITIES = {
        "carnival horizon": 3960,
        "margaritaville at sea islander": 2680,
        "celebrity summit": 2158,
        "msc poesia": 2550,
        "norwegian joy": 3883,
        "carnival dream": 3646,
        "msc seascape": 5632,
        "disney treasure": 4000,
        "carnival celebration": 5282,
        "norwegian prima": 3099,
        "celebrity beyond": 3260,
        "viking mars": 930,
        "royal caribbean oasis": 6771,
        "world navigator": 196,
        "aidaprima": 3286,
        "costa pacifica": 3780,
        "holland america eurodam": 2104,
        "princess grand": 3140,
        "celebrity equinox": 2852,
        "carnival sunrise": 2984,
        "norwegian epic": 4100,
        "explorer of the seas": 3114,
        "symphony of the seas": 6680,
        "harmony of the seas": 5479,
        "allure of the seas": 5484,
        "oasis of the seas": 5400,
        "wonder of the seas": 5734,
        "icon of the seas": 5610,
        "star of the seas": 5610
    };

    // ============================================================
    // JAMAICA CLOCK
    // ============================================================

    function renderClock() {
        const now = new Date();

        // Jamaica is UTC-5 year-round.
        const jamaicaTime =
            new Date(now.getTime() - (5 * 60 * 60 * 1000));

        let hours = jamaicaTime.getUTCHours();
        const minutes = jamaicaTime.getUTCMinutes();
        const ampm = hours >= 12 ? 'PM' : 'AM';

        hours = hours % 12;
        if (hours === 0) hours = 12;

        const timeStr =
            `${hours}:${String(minutes).padStart(2, '0')}`;

        if (liveClockEl) {
            liveClockEl.textContent = timeStr;
        }

        if (liveAmpmEl) {
            liveAmpmEl.textContent = ampm;
        }

        const days = [
            'Sunday',
            'Monday',
            'Tuesday',
            'Wednesday',
            'Thursday',
            'Friday',
            'Saturday'
        ];

        const months = [
            'January',
            'February',
            'March',
            'April',
            'May',
            'June',
            'July',
            'August',
            'September',
            'October',
            'November',
            'December'
        ];

        const dateStr =
            `${days[jamaicaTime.getUTCDay()]}, ` +
            `${months[jamaicaTime.getUTCMonth()]} ` +
            `${jamaicaTime.getUTCDate()}, ` +
            `${jamaicaTime.getUTCFullYear()}`;

        if (liveDateEl) {
            liveDateEl.textContent = dateStr;
        }

        const locationEl =
            document.querySelector('.jamaica-time .location');

        if (locationEl) {
            locationEl.textContent = 'LOCAL TIME (EST)';
        }

        const infoTextEl =
            document.querySelector('.cruise-footer .info-text');

        if (infoTextEl) {
            infoTextEl.innerHTML =
                `All times are local (EST)<br>` +
                `Information subject to change`;
        }
    }

    // ============================================================
    // DATE FUNCTIONS
    // ============================================================

    function getTargetDate() {
        const urlParams =
            new URLSearchParams(window.location.search);

        const dateParam =
            urlParams.get('date');

        if (
            dateParam &&
            /^\d{4}-\d{2}-\d{2}$/.test(dateParam)
        ) {
            return dateParam;
        }

        const now = new Date();

        const jamaicaTime =
            new Date(now.getTime() - (5 * 60 * 60 * 1000));

        const year =
            jamaicaTime.getUTCFullYear();

        const month =
            String(jamaicaTime.getUTCMonth() + 1)
                .padStart(2, '0');

        const day =
            String(jamaicaTime.getUTCDate())
                .padStart(2, '0');

        return `${year}-${month}-${day}`;
    }

    function formatTime12Hour(timeStr) {
        if (!timeStr || timeStr === '--:--') {
            return '--:--';
        }

        const parts =
            timeStr.split(':');

        if (parts.length < 2) {
            return timeStr;
        }

        let hours =
            parseInt(parts[0], 10);

        const minutes =
            parts[1];

        const ampm =
            hours >= 12 ? 'PM' : 'AM';

        hours =
            hours % 12;

        if (hours === 0) {
            hours = 12;
        }

        return (
            `${String(hours).padStart(2, '0')}:` +
            `${minutes} ${ampm}`
        );
    }

    function formatDateDisplay(dateStr) {
        if (!dateStr) {
            return '---';
        }

        const parts =
            dateStr.split('-');

        if (parts.length < 3) {
            return dateStr;
        }

        const months = [
            'Jan',
            'Feb',
            'Mar',
            'Apr',
            'May',
            'Jun',
            'Jul',
            'Aug',
            'Sep',
            'Oct',
            'Nov',
            'Dec'
        ];

        const monthIdx =
            parseInt(parts[1], 10) - 1;

        const day =
            parseInt(parts[2], 10);

        return `${months[monthIdx]} ${day}`;
    }

    function timeToMinutes(timeStr) {
        if (!timeStr || timeStr === '--:--') {
            return 9999;
        }

        const match12 =
            timeStr.match(
                /(\d+):(\d+)\s*(AM|PM)/i
            );

        if (match12) {
            let hours =
                parseInt(match12[1], 10);

            const minutes =
                parseInt(match12[2], 10);

            const ampm =
                match12[3].toUpperCase();

            if (
                ampm === 'PM' &&
                hours < 12
            ) {
                hours += 12;
            }

            if (
                ampm === 'AM' &&
                hours === 12
            ) {
                hours = 0;
            }

            return (
                hours * 60 +
                minutes
            );
        }

        const parts =
            timeStr.split(':');

        if (parts.length >= 2) {
            return (
                parseInt(parts[0], 10) * 60 +
                parseInt(parts[1], 10)
            );
        }

        return 9999;
    }

    // ============================================================
    // SHIP STATUS
    // ============================================================

    function calculateStatus(
        arriveTimeStr,
        departTimeStr,
        shipDateStr,
        todayDateStr
    ) {

        if (shipDateStr > todayDateStr) {
            return 'Scheduled';
        }

        if (shipDateStr < todayDateStr) {
            return 'Departed';
        }

        const now =
            new Date();

        const jamaicaTime =
            new Date(
                now.getTime() -
                (5 * 60 * 60 * 1000)
            );

        const currentMinutes =
            jamaicaTime.getUTCHours() * 60 +
            jamaicaTime.getUTCMinutes();

        const arrMin =
            timeToMinutes(arriveTimeStr);

        const depMin =
            timeToMinutes(departTimeStr);

        if (
            arrMin === 9999 &&
            depMin === 9999
        ) {
            return 'Scheduled';
        }

        if (
            arrMin !== 9999 &&
            depMin !== 9999
        ) {

            if (currentMinutes < arrMin) {
                return 'Expected';
            }

            if (
                currentMinutes >= arrMin &&
                currentMinutes <= depMin
            ) {
                return 'In Port';
            }

            return 'Departed';
        }

        if (arrMin !== 9999) {
            return (
                currentMinutes < arrMin
                    ? 'Expected'
                    : 'In Port'
            );
        }

        if (depMin !== 9999) {
            return (
                currentMinutes <= depMin
                    ? 'In Port'
                    : 'Departed'
            );
        }

        return 'Scheduled';
    }

    // ============================================================
    // PORT FUNCTIONS
    // ============================================================

    function getPortClass(port) {
        const name =
            (port || '')
                .toLowerCase();

        if (name.includes('montego')) {
            return 'port-montego';
        }

        if (name.includes('falmouth')) {
            return 'port-falmouth';
        }

        if (name.includes('ocho')) {
            return 'port-ocho';
        }

        if (name.includes('kingston')) {
            return 'port-kingston';
        }

        return '';
    }

    function cleanPortName(port) {
        const name =
            (port || '')
                .toLowerCase()
                .trim();

        if (name.includes('montego')) {
            return 'Montego Bay';
        }

        if (name.includes('falmouth')) {
            return 'Falmouth';
        }

        if (name.includes('ocho')) {
            return 'Ocho Rios';
        }

        if (name.includes('kingston')) {
            return 'Kingston';
        }

        return port;
    }

    // ============================================================
    // STATUS BADGES
    // ============================================================

    function getStatusBadge(status) {
        const stat =
            (status || '')
                .toLowerCase()
                .trim();

        if (stat === 'in port') {
            return (
                `<span class="status-badge badge-in-port">` +
                `IN PORT</span>`
            );
        }

        if (stat === 'expected') {
            return (
                `<span class="status-badge badge-expected">` +
                `EXPECTED</span>`
            );
        }

        if (stat === 'scheduled') {
            return (
                `<span class="status-badge badge-scheduled">` +
                `SCHEDULED</span>`
            );
        }

        if (stat === 'departed') {
            return (
                `<span class="status-badge badge-departed">` +
                `DEPARTED</span>`
            );
        }

        if (stat === 'cancelled') {
            return (
                `<span class="status-badge badge-cancelled">` +
                `CANCELLED</span>`
            );
        }

        return (
            `<span class="status-badge">` +
            `${(status || '').toUpperCase()}` +
            `</span>`
        );
    }

    // ============================================================
    // SCREEN HEIGHT
    // ============================================================

    function adjustTableContainerHeight() {
        const tableContainer =
            document.querySelector(
                '.table-container'
            );

        if (!tableContainer) {
            return;
        }

        const header =
            document.querySelector(
                'body > header'
            );

        const cruise =
            document.querySelector(
                '.cruise'
            );

        const dashboardHeader =
            document.querySelector(
                '.dashboard-header'
            );

        const statsPanel =
            document.querySelector(
                '.stats-panel'
            );

        const footerLegend =
            document.querySelector(
                '.footer-legend'
            );

        const cruiseFooter =
            document.querySelector(
                '.cruise-footer'
            );

        const headerHeight =
            header
                ? header.offsetHeight
                : 0;

        const cruiseHeight =
            cruise
                ? cruise.offsetHeight
                : 0;

        const footerHeight =
            cruiseFooter
                ? cruiseFooter.offsetHeight
                : 0;

        const dashboard =
            document.querySelector(
                '.cruise-dashboard'
            );

        let dashboardPadding = 0;

        if (dashboard) {
            const style =
                window.getComputedStyle(
                    dashboard
                );

            dashboardPadding =
                parseFloat(style.paddingTop) +
                parseFloat(style.paddingBottom);
        }

        const dashboardHeaderHeight =
            dashboardHeader
                ? dashboardHeader.offsetHeight
                : 0;

        let dashboardHeaderMargin = 0;

        if (dashboardHeader) {
            const style =
                window.getComputedStyle(
                    dashboardHeader
                );

            dashboardHeaderMargin =
                parseFloat(style.marginTop) +
                parseFloat(style.marginBottom);
        }

        const statsPanelHeight =
            statsPanel
                ? statsPanel.offsetHeight
                : 0;

        let statsPanelMargin = 0;

        if (statsPanel) {
            const style =
                window.getComputedStyle(
                    statsPanel
                );

            statsPanelMargin =
                parseFloat(style.marginTop) +
                parseFloat(style.marginBottom);
        }

        const footerLegendHeight =
            footerLegend
                ? footerLegend.offsetHeight
                : 0;

        let footerLegendMargin = 0;

        if (footerLegend) {
            const style =
                window.getComputedStyle(
                    footerLegend
                );

            footerLegendMargin =
                parseFloat(style.marginTop) +
                parseFloat(style.marginBottom);
        }

        let tableContainerMargin = 0;

        if (tableContainer) {
            const style =
                window.getComputedStyle(
                    tableContainer
                );

            tableContainerMargin =
                parseFloat(style.marginTop) +
                parseFloat(style.marginBottom);
        }

        const totalSubtract =
            headerHeight +
            cruiseHeight +
            footerHeight +
            dashboardPadding +
            dashboardHeaderHeight +
            dashboardHeaderMargin +
            statsPanelHeight +
            statsPanelMargin +
            footerLegendHeight +
            footerLegendMargin +
            tableContainerMargin;

        const viewportHeight =
            window.innerHeight;

        const availableHeight =
            viewportHeight -
            totalSubtract -
            5;

        tableContainer.style.height =
            `${Math.max(
                200,
                availableHeight
            )}px`;
    }

    // ============================================================
    // LOAD CRUISE DATA
    // ============================================================

    async function fetchAndRenderData() {

        const targetDate =
            getTargetDate();

        tableBodyEl.innerHTML = `
            <tr class="loading-row">
                <td colspan="6">
                    <div class="spinner"></div>
                    <div class="loading-text">
                        Fetching Jamaica Arrivals...
                    </div>
                </td>
            </tr>
        `;

        try {

            // Read the JSON generated securely by GitHub Actions.
            // Timestamp prevents browser/NoviSign caching.
            const response = await fetch(
                `${CRUISE_DATA_URL}?t=${Date.now()}`,
                {
                    cache: 'no-store'
                }
            );

            if (!response.ok) {
                throw new Error(
                    `HTTP error! status: ${response.status}`
                );
            }

            const data =
                await response.json();

            if (!Array.isArray(data)) {
                throw new Error(
                    'Cruise data is not in the expected format.'
                );
            }

            // Aggregate arrivals from all ports
            const arrivals = [];

            let lastScrapedTime = 0;

            data.forEach(item => {

                if (item.recordType === 'port') {

                    const portName =
                        item.name;

                    const portArrivals =
                        item.upcomingArrivals || [];

                    portArrivals.forEach(arr => {

                        arrivals.push({
                            ...arr,
                            portName: portName
                        });

                    });

                    if (item.scrapedAt) {

                        const t =
                            new Date(
                                item.scrapedAt
                            ).getTime();

                        if (t > lastScrapedTime) {
                            lastScrapedTime = t;
                        }
                    }
                }
            });

            // Determine whether a specific date was requested
            const urlParams =
                new URLSearchParams(
                    window.location.search
                );

            const dateParam =
                urlParams.get('date');

            let filteredArrivals = [];
            let isSingleDate = false;

            if (
                dateParam &&
                /^\d{4}-\d{2}-\d{2}$/.test(dateParam)
            ) {

                filteredArrivals =
                    arrivals.filter(
                        arr =>
                            arr.date === dateParam
                    );

                isSingleDate = true;

            } else {

                // Show all upcoming arrivals
                filteredArrivals =
                    arrivals.filter(
                        arr =>
                            arr.date >= targetDate
                    );

                isSingleDate = false;
            }

            // ====================================================
            // LABELS
            // ====================================================

            const shipsLabelEl =
                document.querySelector(
                    '.ships .stat-label'
                );

            const passengersLabelEl =
                document.querySelector(
                    '.passengers .stat-label'
                );

            const portsLabelEl =
                document.querySelector(
                    '.ports .stat-label'
                );

            const firstHeaderEl =
                document.querySelector(
                    '.arrivals-table th:first-child'
                );

            if (isSingleDate) {

                if (shipsLabelEl) {
                    shipsLabelEl.textContent =
                        'Ships Today';
                }

                if (passengersLabelEl) {
                    passengersLabelEl.textContent =
                        'Passengers Today';
                }

                if (portsLabelEl) {
                    portsLabelEl.textContent =
                        'Ports Active';
                }

                if (firstHeaderEl) {
                    firstHeaderEl.textContent =
                        'PORT';
                }

            } else {

                if (shipsLabelEl) {
                    shipsLabelEl.textContent =
                        'Upcoming Ships';
                }

                if (passengersLabelEl) {
                    passengersLabelEl.textContent =
                        'Upcoming Guests';
                }

                if (portsLabelEl) {
                    portsLabelEl.textContent =
                        'Active Ports';
                }

                if (firstHeaderEl) {
                    firstHeaderEl.textContent =
                        'DATE';
                }
            }

            // ====================================================
            // KPI CALCULATIONS
            // ====================================================

            const totalShips =
                filteredArrivals.length;

            let totalPassengers = 0;

            const activePortsSet =
                new Set();

            filteredArrivals.sort(
                (a, b) => {

                    if (a.date !== b.date) {
                        return a.date.localeCompare(
                            b.date
                        );
                    }

                    return (
                        timeToMinutes(
                            a.arrivalTime
                        ) -
                        timeToMinutes(
                            b.arrivalTime
                        )
                    );
                }
            );

            filteredArrivals.forEach(arr => {

                const shipKey =
                    (arr.shipName || '')
                        .toLowerCase()
                        .trim();

                const capacity =
                    SHIP_CAPACITIES[shipKey] || 0;

                arr.Guests =
                    capacity;

                arr.Status =
                    calculateStatus(
                        arr.arrivalTime,
                        arr.departureTime,
                        arr.date,
                        targetDate
                    );

                totalPassengers +=
                    capacity;

                if (
                    arr.Status
                        .toLowerCase()
                        .trim() !==
                    'cancelled'
                ) {

                    activePortsSet.add(
                        cleanPortName(
                            arr.portName
                        )
                    );
                }
            });

            if (kpiShipsEl) {
                kpiShipsEl.textContent =
                    totalShips;
            }

            if (kpiPassengersEl) {
                kpiPassengersEl.textContent =
                    totalPassengers > 0
                        ? totalPassengers
                            .toLocaleString('en-CA')
                        : '0';
            }

            if (kpiPortsEl) {
                kpiPortsEl.textContent =
                    activePortsSet.size;
            }

            updateLastUpdatedTimestamp();

            // ====================================================
            // RENDER TABLE
            // ====================================================

            tableBodyEl.innerHTML = '';

            if (
                filteredArrivals.length === 0
            ) {

                tableBodyEl.innerHTML = `
                    <tr class="loading-row">
                        <td
                            colspan="6"
                            style="
                                padding:50px;
                                font-size:20px;
                                color:var(--text-muted);
                            "
                        >
                            No cruise ship arrivals scheduled.
                        </td>
                    </tr>
                `;

                adjustTableContainerHeight();
                return;
            }

            filteredArrivals.forEach(arr => {

                const tr =
                    document.createElement(
                        'tr'
                    );

                const guestsFormatted =
                    arr.Guests > 0
                        ? arr.Guests
                            .toLocaleString('en-CA')
                        : '---';

                const cleanedPort =
                    cleanPortName(
                        arr.portName
                    );

                const firstColumnHTML =
                    isSingleDate
                        ? `
                            <td class="${getPortClass(arr.portName)}">
                                ${cleanedPort.toUpperCase()}
                            </td>
                        `
                        : `
                            <td class="${getPortClass(arr.portName)}">
                                <div style="font-weight:700;">
                                    ${formatDateDisplay(arr.date)}
                                </div>

                                <div
                                    style="
                                        font-size:16px;
                                        opacity:0.85;
                                        font-weight:600;
                                        margin-top:4px;
                                    "
                                >
                                    ${cleanedPort.toUpperCase()}
                                </div>
                            </td>
                        `;

                tr.innerHTML = `
                    ${firstColumnHTML}

                    <td>
                        ${formatTime12Hour(
                            arr.arrivalTime
                        )}
                    </td>

                    <td style="font-weight:700;">
                        ${arr.shipName}
                    </td>

                    <td>
                        ${formatTime12Hour(
                            arr.departureTime
                        )}
                    </td>

                    <td>
                        ${guestsFormatted}
                    </td>

                    <td>
                        ${getStatusBadge(
                            arr.Status
                        )}
                    </td>
                `;

                tableBodyEl.appendChild(
                    tr
                );
            });

            adjustTableContainerHeight();

        } catch (error) {

            console.error(
                'Error loading cruise schedule:',
                error
            );

            tableBodyEl.innerHTML = `
                <tr class="error-row">
                    <td
                        colspan="6"
                        style="
                            padding:50px;
                            font-size:20px;
                            color:#ff5252;
                        "
                    >
                        Error loading schedule data.
                    </td>
                </tr>
            `;

            adjustTableContainerHeight();
        }
    }

    // ============================================================
    // INITIALIZATION
    // ============================================================

    updateLastUpdatedTimestamp();

    fetchAndRenderData();

    window.addEventListener(
        'resize',
        adjustTableContainerHeight
    );

    renderClock();

    setInterval(
        renderClock,
        1000
    );

    // This only rereads cruise-data.json.
    // It does NOT trigger a paid Apify run.
    setInterval(
        fetchAndRenderData,
        AUTO_REFRESH_INTERVAL
    );

});
